<?php

   Class Model extends CI_Model {

   	   public function __construct() {
   	   	   parent::__construct();
   	   }

   	   public function test() {
   	   	   echo "This text is generated by the model";
   	   }
   }

?>